### ISSUE TITLE
Exception when starting Runtime

### ISSUE THREAD

**Issue by MovingBitsGroupRoth** [tyronegroves/SimpleCQRS#10]
Hi,

I'm getting the following exception a few times when the runtime is starting:

A first chance exception of type 'System.Threading.SynchronizationLockException' occurred in Microsoft.Practices.Unity.dll

It happens in the SimpleCqrsDemo and in my own project.
Past the exception everything works fine. Weird :-)

ciao
Volker

**Comment by tyronegroves** [comment]
Hi Volker,

Thanks for taking interest in the project.  The exception is actually being thrown by Unity and caught and handled internally in the Microsoft.Practices.Unity.dll.  That message will show in the Output window when an exception is throw and caught in a try catch block.

Thanks,
Tyrone
