### ISSUE TITLE
Look ma, no commandhandlers!

### ISSUE THREAD

**Issue by geoffreysmith** [tyronegroves/SimpleCQRS#18]
90% of commandhandlers only do the following:
1. Determine whether they are creating the aggregate root or not
2. Find the aggregate root (or create it)
3. Invoke a method on the aggregate root.

I think these can all be accomplished via attributes on the command. The following is a command handler, with an aggregate root of "User" and invokes a method of "ChangeAddress":

```
    [CommandHandler(AggregateRootAction.Update, typeof(User))]
    public class UpdateUserAddressCommand : ICommand
```

You'd have to assume the method off the aggregate root is the same as the class name, sans the Command at the end. This is actually pretty easy. I'm not going to actually implement it because it is NYE.

**Comment by darrencauthon** [comment]
Well, now it's not NYE.  And you have Monday off.  So I agree with you, and you should implement it.  :)

**Comment by geoffreysmith** [comment]
Delegation is a skill a lot of engineers to do not have, so I am practicing.

**Comment by darrencauthon** [comment]
Nobody else will do it.  I'm not going to actively develop in .Net through Visual Studio Express.

I was thinking, instead of using the attributes you could use a convention based on the name of the command.  If it is "UpdateUserAddressCommand," just go ahead and use an update handler.  

I believe you could probably update the command invoker in the runtime, so you could try this out without changing SimpleCQRS directly.

**Comment by geoffreysmith** [comment]
I was thinking of that approach but I kept running into two problems:
1. Using convention leads to the creation of awkwardly named commands. This is not a huge deal, but more of a personal style issue.
2. I like the idea of explicitly stating that a command doesn't have a commandhandler. If I have a commandhandler I created for a command, and it can't find the commandhandler, I want simplecqrs to throw an exception and not attempt to create a commandhandler. This could be achieved through attributes [UseCustomCommandHandler], which may be cleaner, but I haven't quite figured it out.

I was joking on the delegation issue, this is a simple thing to update.

**Comment by darrencauthon** [comment]
Well, any good convention has a way to eject out when it doesn't fit.  You could use a convention that handled everything for you based on something like an "Update" prefix, and then use the attributes in the cases when you want to do it declaratively.
